server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jiaqing
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/*
logging:
  config: classpath:logback-spring.xml
  level:
    com.abby.jiaqing: debug
  path: /data/logs